# title: Process Cleaned Data
# author: Sarah Bitter

# load libraries
source(here::here("always_run","libraries.R"))

#### Load data, clean variable names ####
data_09_21 <- read_feather(here::here("data_processed", "data_09_21"))

data_09_21 <- data_09_21 %>% janitor::clean_names()

data_09_21 <- data_09_21 %>% mutate(position = toupper(position),
                                    employer_name = toupper(employer_name))

rds_data <- data_09_21 %>% filter(grepl("RESEARCH DATA ANALYST", position) | 
                                    grepl("RESEARCH ANALYST", position) |
                                    grepl("RESEARCH DATA SPECIALIST", position) |
                                    grepl("RESEARCH PROGRAM SPECIALIST", position) |
                                    grepl("RESEARCH DATA SUPERVISOR", position) |
                                    grepl("RESEARCH DATA MANAGER", position) |
                                    grepl("RESEARCH MANAGER", position) |
                                    grepl("CHIEF OF RESEARCH CORRECTIONAL PROGRAM", position) |
                                    grepl("TAX RESEARCH SPECIALIST", position))
####  

#### Create RDS name, class, and range variables ####
# Create variable storing RDS name for pre-RDS positions
# Create dataset with RDS name and RDS class for matching
rds_name_matching_data <- data.frame(rds_name = c("RESEARCH DATA ANALYST II -GENERAL-, RANGE A",
                                                  "RESEARCH DATA SUPERVISOR II -GENERAL-",
                                                  "RESEARCH DATA SPECIALIST I",
                                                  "RESEARCH DATA SPECIALIST II",
                                                  "RESEARCH DATA ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE C",
                                                  "RESEARCH DATA ANALYST I -GENERAL-, RANGE C",
                                                  "RESEARCH DATA ANALYST II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA SPECIALIST I (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA SPECIALIST III (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA SPECIALIST II -SOCIAL/BEHAVIORAL-",
                                                  "RESEARCH DATA MANAGER",
                                                  "RESEARCH DATA SUPERVISOR I -GENERAL-",
                                                  "RESEARCH DATA SUPERVISOR II -SOCIAL/BEHAVIORAL",
                                                  "RESEARCH MANAGER -SOCIAL/BEHAVIORAL-",
                                                  "RESEARCH DATA SPECIALIST I -SOCIAL/BEHAVIORAL-",
                                                  "RESEARCH DATA SPECIALIST II (DEMOGRAPHY)",
                                                  "RESEARCH DATA SPECIALIST III (DEMOGRAPHY)",
                                                  "RESEARCH DATA ANALYST II (ECONOMICS)",
                                                  "RESEARCH DATA SPECIALIST II (ECONOMICS), RANGE A",
                                                  "RESEARCH DATA ANALYST II -GENERAL-, RANGE L",
                                                  "RESEARCH DATA ANALYST I -GENERAL-, RANGE A",
                                                  "RESEARCH DATA ANALYST I -GENERAL-, RANGE B",
                                                  "RESEARCH MANAGER -GENERAL-",
                                                  "RESEARCH DATA SPECIALIST I (ECONOMICS), RANGE A",
                                                  "RESEARCH DATA SUPERVISOR I (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA ANALYST II (DEMOGRAPHY)",
                                                  "RESEARCH DATA SUPERVISOR II (DEMOGRAPHY)",
                                                  "RESEARCH MANAGER (DEMOGRAPHY)",
                                                  "RESEARCH DATA SPECIALIST I (DEMOGRAPHY)",
                                                  "RESEARCH DATA SPECIALIST II (ECONOMICS), RANGE L",
                                                  "RESEARCH DATA SPECIALIST III (FINANCE ECONOMICS)",
                                                  "RESEARCH DATA SUPERVISOR II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA SPECIALIST II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA ANALYST I (ECONOMICS), RANGE C",
                                                  "RESEARCH DATA SUPERVISOR I (ECONOMICS)",
                                                  "RESEARCH DATA SUPERVISOR II (ECONOMICS)",
                                                  "RESEARCH DATA ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE A",
                                                  "RESEARCH DATA ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE B",
                                                  "RESEARCH DATA SPECIALIST II (FIRE AND FUELS)",
                                                  "NA",
                                                  "RESEARCH DATA SPECIALIST I",
                                                  "RESEARCH DATA SPECIALIST II",
                                                  "RESEARCH DATA SPECIALIST III",
                                                  "RESEARCH DATA SPECIALIST II -HEALTH-",
                                                  "RESEARCH DATA SPECIALIST I (HEALTH)",
                                                  "RESEARCH DATA ANALYST I (ECONOMICS), RANGE A",
                                                  "RESEARCH DATA ANALYST I (ECONOMICS), RANGE B",
                                                  "RESEARCH DATA ANALYST, RANGE C",
                                                  "NA",
                                                  "NA",
                                                  "RESEARCH DATA ANALYST I (SOCIAL/BEHAVIORAL), RANGE C",
                                                  "RESEARCH DATA ANALYST II -SOCIAL/BEHAVIORAL-",
                                                  "RESEARCH DATA SPECIALIST II (MENTAL HEALTH)",
                                                  "RESEARCH DATA SUPERVISOR I -SOCIAL/BEHAVIORAL-",
                                                  "RESEARCH DATA SPECIALIST III (TRANSPORTATION ECONOMICS)",
                                                  "RESEARCH MANAGER (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                  "RESEARCH DATA SPECIALIST III (RESOURCE ECONOMICAL OPERATIONS RESEARCH)",
                                                  "RESEARCH DATA ANALYST I (DEMOGRAPHY), RANGE C",
                                                  "RESEARCH DATA SPECIALIST II, RANGE A",
                                                  "RESEARCH DATA SPECIALIST III (DEMOGRAPHY), RANGE A",
                                                  "RESEARCH DATA ANALYST II (DEMOGRAPHY), RANGE L",
                                                  "RESEARCH DATA SPECIALIST II (DEMOGRAPHY), RANGE L",
                                                  "RESEARCH DATA SPECIALIST III (DEMOGRAPHY), RANGE L",
                                                  "RESEARCH DATA ANALYST I -GENERAL-, RANGE N",
                                                  "RESEARCH DATA SPECIALIST II, RANGE L",
                                                  "RESEARCH DATA SPECIALIST II (DEMOGRAPHY), RANGE A",
                                                  "RESEARCH DATA ANALYST I, RANGE A",
                                                  "RESEARCH DATA ANALYST I, RANGE B",
                                                  "RESEARCH DATA ANALYST I, RANGE C",
                                                  "RESEARCH DATA ANALYST I, RANGE L",
                                                  "RESEARCH DATA ANALYST I, RANGE N",
                                                  "RESEARCH DATA ANALYST II, RANGE A",
                                                  "RESEARCH DATA ANALYST II, RANGE L",
                                                  "RESEARCH DATA MANAGER",
                                                  "RESEARCH DATA SPECIALIST I",
                                                  "RESEARCH DATA SPECIALIST I, RANGE A",
                                                  "RESEARCH DATA SPECIALIST I, RANGE L",
                                                  "RESEARCH DATA SPECIALIST II, RANGE A",
                                                  "RESEARCH DATA SPECIALIST II, RANGE L",
                                                  "RESEARCH DATA SPECIALIST III, RANGE A",
                                                  "RESEARCH DATA SPECIALIST III, RANGE L",
                                                  "RESEARCH DATA SUPERVISOR I",
                                                  "RESEARCH DATA SUPERVISOR II"),
                                     position = c("RESEARCH ANALYST II -GENERAL-, RANGE A",
                                                      "RESEARCH MANAGER II -GENERAL-",
                                                      "RESEARCH PROGRAM SPECIALIST I",
                                                      "RESEARCH PROGRAM SPECIALIST II",
                                                      "RESEARCH ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE C",
                                                      "RESEARCH ANALYST I -GENERAL-, RANGE C",
                                                      "RESEARCH ANALYST II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH PROGRAM SPECIALIST I (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH PROGRAM SPECIALIST III (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH PROGRAM SPECIALIST II -SOCIAL/BEHAVIORAL-",
                                                      "CHIEF OF RESEARCH CORRECTIONAL PROGRAM",
                                                      "RESEARCH MANAGER I -GENERAL-",
                                                      "RESEARCH MANAGER II -SOCIAL/BEHAVIORAL",
                                                      "RESEARCH MANAGER III -SOCIAL/BEHAVIORAL-",
                                                      "RESEARCH PROGRAM SPECIALIST I -SOCIAL/BEHAVIORAL-",
                                                      "RESEARCH PROGRAM SPECIALIST II (DEMOGRAPHY)",
                                                      "RESEARCH PROGRAM SPECIALIST III (DEMOGRAPHY)",
                                                      "RESEARCH ANALYST II (ECONOMICS)",
                                                      "RESEARCH PROGRAM SPECIALIST II (ECONOMICS), RANGE A",
                                                      "RESEARCH ANALYST II -GENERAL-, RANGE L",
                                                      "RESEARCH ANALYST I -GENERAL-, RANGE A",
                                                      "RESEARCH ANALYST I -GENERAL-, RANGE B",
                                                      "RESEARCH MANAGER III -GENERAL-",
                                                      "RESEARCH PROGRAM SPECIALIST I (ECONOMICS), RANGE A",
                                                      "RESEARCH MANAGER I (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH ANALYST II (DEMOGRAPHY)",
                                                      "RESEARCH MANAGER II (DEMOGRAPHY)",
                                                      "RESEARCH MANAGER III (DEMOGRAPHY)",
                                                      "RESEARCH PROGRAM SPECIALIST I (DEMOGRAPHY)",
                                                      "RESEARCH PROGRAM SPECIALIST II (ECONOMICS), RANGE L",
                                                      "RESEARCH PROGRAM SPECIALIST III (FINANCE ECONOMICS)",
                                                      "RESEARCH MANAGER II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH PROGRAM SPECIALIST II (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH ANALYST I (ECONOMICS), RANGE C",
                                                      "RESEARCH MANAGER I (ECONOMICS)",
                                                      "RESEARCH MANAGER II (ECONOMICS)",
                                                      "RESEARCH ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE A",
                                                      "RESEARCH ANALYST I (GEOGRAPHIC INFORMATION SYSTEMS), RANGE B",
                                                      "RESEARCH PROGRAM SPECIALIST II (FIRE AND FUELS)",
                                                      "ASSOCIATE TAX RESEARCH SPECIALIST",
                                                      "TAX RESEARCH SPECIALIST I",
                                                      "TAX RESEARCH SPECIALIST II",
                                                      "TAX RESEARCH SPECIALIST III",
                                                      "RESEARCH PROGRAM SPECIALIST II -HEALTH-",
                                                      "RESEARCH PROGRAM SPECIALIST I (HEALTH)",
                                                      "RESEARCH ANALYST I (ECONOMICS), RANGE A",
                                                      "RESEARCH ANALYST I (ECONOMICS), RANGE B",
                                                      "RESEARCH ANALYST, RANGE C",
                                                      "SENIOR RESEARCH ANALYST, RANGE C",
                                                      "SUPERVISING RESEARCH ANALYST, RANGE C",
                                                      "RESEARCH ANALYST I (SOCIAL/BEHAVIORAL), RANGE C",
                                                      "RESEARCH ANALYST II -SOCIAL/BEHAVIORAL-",
                                                      "RESEARCH PROGRAM SPECIALIST II (MENTAL HEALTH)",
                                                      "RESEARCH MANAGER I -SOCIAL/BEHAVIORAL-",
                                                      "RESEARCH PROGRAM SPECIALIST III (TRANSPORTATION ECONOMICS)",
                                                      "RESEARCH MANAGER III (GEOGRAPHIC INFORMATION SYSTEMS)",
                                                      "RESEARCH PROGRAM SPECIALIST III (RESOURCE ECONOMICAL OPERATIONS RESEARCH)",
                                                      "RESEARCH ANALYST I (DEMOGRAPHY), RANGE C",
                                                      "RESEARCH PROGRAM SPECIALIST II, RANGE A",
                                                      "RESEARCH PROGRAM SPECIALIST III (DEMOGRAPHY), RANGE A",
                                                      "RESEARCH ANALYST II (DEMOGRAPHY), RANGE L",
                                                      "RESEARCH PROGRAM SPECIALIST II (DEMOGRAPHY), RANGE L",
                                                      "RESEARCH PROGRAM SPECIALIST III (DEMOGRAPHY), RANGE L",
                                                      "RESEARCH ANALYST I -GENERAL-, RANGE N",
                                                      "RESEARCH PROGRAM SPECIALIST II, RANGE L",
                                                      "RESEARCH PROGRAM SPECIALIST II (DEMOGRAPHY), RANGE A",
                                                      "RESEARCH DATA ANALYST I, RANGE A",
                                                      "RESEARCH DATA ANALYST I, RANGE B",
                                                      "RESEARCH DATA ANALYST I, RANGE C",
                                                      "RESEARCH DATA ANALYST I, RANGE L",
                                                      "RESEARCH DATA ANALYST I, RANGE N",
                                                      "RESEARCH DATA ANALYST II, RANGE A",
                                                      "RESEARCH DATA ANALYST II, RANGE L",
                                                      "RESEARCH DATA MANAGER",
                                                      "RESEARCH DATA SPECIALIST I",
                                                      "RESEARCH DATA SPECIALIST I, RANGE A",
                                                      "RESEARCH DATA SPECIALIST I, RANGE L",
                                                      "RESEARCH DATA SPECIALIST II, RANGE A",
                                                      "RESEARCH DATA SPECIALIST II, RANGE L",
                                                      "RESEARCH DATA SPECIALIST III, RANGE A",
                                                      "RESEARCH DATA SPECIALIST III, RANGE L",
                                                      "RESEARCH DATA SUPERVISOR I",
                                                      "RESEARCH DATA SUPERVISOR II"),
                                     rds_class = c("RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SUPERVISOR II",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA MANAGER",
                                                   "RESEARCH DATA SUPERVISOR I",
                                                   "RESEARCH DATA SUPERVISOR II",
                                                   "RESEARCH MANAGER",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH MANAGER",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SUPERVISOR I",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SUPERVISOR II",
                                                   "RESEARCH MANAGER",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA SUPERVISOR II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA SUPERVISOR I",
                                                   "RESEARCH DATA SUPERVISOR II",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "NA",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST",
                                                   "NA",
                                                   "NA",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SUPERVISOR I",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH MANAGER",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST I",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA ANALYST II",
                                                   "RESEARCH DATA MANAGER",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST I",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST II",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA SPECIALIST III",
                                                   "RESEARCH DATA SUPERVISOR I",
                                                   "RESEARCH DATA SUPERVISOR II"))
# Merge in RDS names and classes
rds_data <- merge(rds_data,
                  rds_name_matching_data,
                  by.x = c("position"),
                  all.x = TRUE)

# Relocate variables and create NAs
rds_data <- rds_data %>% relocate(c(rds_class, rds_name, position), .after = department_or_subdivision) %>%
  mutate(rds_name = na_if(rds_name, "NA"),
         rds_class = na_if(rds_class, "NA"))

# Sort data
rds_data <- rds_data %>% arrange(year, employer_name, department_or_subdivision, position)

# Create range variable and place after class variable
rds_data <- rds_data %>% mutate(range = ifelse(grepl("RANGE", position), 
                                               substring(position, nchar(position)), 
                                               NA)) %>%
                         relocate(range, .after = rds_class)
####

#### Save processed data ####
rds_data %>% write_feather(here::here("data_processed", "processed_data"))
####